### ISSUE TITLE
Solaris LPEs

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#10583]
This is to help @bcoles and I not collide on PRs.

List of Solaris LPEs:

- [x] ~[extremeparr](https://www.exploit-db.com/exploits/41871/) (@bcoles) - PR #10663~ Merged
- [x] ~[libnspr_priv_esc](https://www.exploit-db.com/exploits/2641/) (@bcoles) - PR #10620~ Merged
- [x] ~[rsh_stack_clash](https://www.exploit-db.com/exploits/42270/) (@bcoles) - PR #10668~ Merged
- [x] ~[pfexec](https://docs.oracle.com/cd/E19253-01/816-4557/prbactm-1/index.html) (@bcoles) - PR #11345~ Merged
- [ ] [avs](https://www.exploit-db.com/exploits/45126/) - N/A
- [ ] [hoagie_solaris_siocgtunparam](https://www.exploit-db.com/exploits/15962/) (@h00die)
- [x] ~[srsexec](https://www.exploit-db.com/exploits/30021/) (@h00die) - PR #10628~ Merged
- [ ] [137097-01](https://www.exploit-db.com/exploits/20418/) (@h00die)
- [ ] [DtPrintinfo/DtSession](https://www.exploit-db.com/exploits/1248/) - N/A

**Comment by h00die** [comment]
It looks like AVS requires Sun StorageTek Availability Suite.  While I can find the documentation for it, I'm not able to find the software itself.  Anyone have it or know where I can find it?  @wvu-r7 you all have anything in the lab by chance? @bcoles any ideas?

**Comment by wvu-r7** [comment]
Nope, not at all.

**Comment by bcoles** [comment]
Apparently, `pkg install avs`

Apparently it also works on Open Solaris, but I haven't tried. Open Indiana may also be an option.

You may or may not need to install and configure Solaris Cluster.

* https://docs.oracle.com/cd/E56676_01/html/E56678/glydk.html
* https://docs.oracle.com/cd/E19359-01/819-6147-10/config_proc.html
* https://docs.oracle.com/cd/E19160-01/html/821-1411/fnrfo.html
* https://docs.oracle.com/cd/E19160-01/html/821-1411/fnkcg.html
* https://docs.oracle.com/cd/E19421-01/819-7196/fpcng/index.html
* https://docs.oracle.com/cd/E19787-01/820-4679/appreplication-1/index.html

**Comment by h00die** [comment]
smh, the docs I read [here](https://docs.oracle.com/cd/E19359-01/819-6147-10/installation.html#47955) said to install 8 packages individually and naturally none of that works.  Spent an hour trying to install and never thought to try `avs`.  Thanks @bcoles

**Comment by h00die** [comment]
AVS installed and i believe configured, however i'm getting a core dump before any output.  I'm def not a C programmer, so at this point unless @mu-b can throw some assistance (or @bcoles) you want to try, I'm going to start looking at other things.

**Comment by h00die** [comment]
dtprininfo may be CVE-2003-1057

**Comment by mu-b** [comment]
Any details of the machine you are trying this against?
uname -a?

**Comment by h00die** [comment]
Don't have it in front of me but it's an 11.3 x86.
No patches installed. Did a PKG install avs and started the service. It created /Dev/sdbc so that was a good sign. Other than maybe adding gcc (forgot if 10 or 11 came with it) and VMware tools, should be a stock image

**Comment by mu-b** [comment]
should work, drop gdb on the machine and grab the output and paste if you can.

**Comment by h00die** [comment]
i think this was mostly covered, going to close it.
