### ISSUE TITLE
Support new CVE Format

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3823]
*This issue was [RM8789](https://dev.metasploit.com/redmine/issues/8789), originally filed by @FireFart*

The CVE format changed this year: http://cve.mitre.org/cve/identifiers/syntaxchange.html

There are a lot of occurences in Code where the correct syntax is verified via Regex.

The correct Syntax for CVE's is now `^\CVE-d{4}\-\d{4,}$ or ^\d{4}\-\d{4,}$` without the CVE identifier.

Code occurrences:

* msftidy check: #3262
* lib/msf/core/db.rb: Some occurences of `/C..-([0-9\-]{9})/`
* and maybe some more.

Seems like we have some time before the first 4+ CVE Identifiers will appear, but this issue should be adressed before.

## TODO

  - [ ] Spec for 4,5, more than five digits.
  - [x] msftidy check
  - [x] Effect any changes needed. I want to say we already tackled this but I don't recall seeing a spec for it.

**Comment by bcook-r7** [comment]
Is this already fixed/ is there anything to do here? If there are still many different separate regex checks, this might be a good time to move it to once place. The current checks seem to be pretty lose - maybe they instead need to be tightened up.

**Comment by wchen-r7** [comment]
It looks like we only need to fix:
msf/core/db_manager/import/qualys/asset.rb:        vuln_refs[qid].push('CVE-' + /C..-([0-9\-]{9})/.match(ref.elements['ID'].text.to_s)[1])
msf/core/db_manager/import/qualys/scan.rb:            refs.push('CVE-' + /C..-([0-9\-]{9})/.match(ref.elements['ID'].text.to_s)[1])

**Comment by todb-r7** [comment]
TODO:

  - [ ] Spec for 4,5, more than five digits.
  - [ ] msftidy check
  - [ ] Effect any changes needed. I want to say we already tackled this but I don't recall seeing a spec for it.

**Comment by wvu-r7** [comment]
What exactly do we want spec'd? This seems really vague.
