### ISSUE TITLE
OSX and BSD x64 payloads do not support any prepend flags

### ISSUE THREAD

**Issue by joevennix** [rapid7/metasploit-framework#5124]
OSX and BSD x64 payloads do not support any prepend flags. They appear to support them, since the mixins `Msf::Payload::Osx` and `Msf::Payload::Bsd` modules include them as  advanced datastore options, but in both instances, the flags are gated with an if:

    if (test_arch.include?(ARCH_X86))

It also appears that all of the x86 implementations of the prepend flags in these mixins use the exact same code. Keeping OSX/BSD payload mixins separate definitely makes sense, but I think we should DRY the duplicated prepend flag code into a mixin. Iirc in x64 OSX makes some changes to bsd's syscall numbers, so I don't think we'll be able to DRY up x64 code.

**Comment by joevennix** [comment]
This was noticed by @wvu-r7 in #5119, where he was able to use zsh as a workaround.

**Comment by joevennix** [comment]
#### Roadmap
- [ ] Fix osx x64 prepends
- [ ] Fix bsd x64 prepends
- [ ] DRY up osx/bsd x86 prepends and shellcode

**Comment by bcook-r7** [comment]
Thanks for looking at this Joe.

**Comment by wvu-r7** [comment]
Thanks, @joevennix!
