### ISSUE TITLE
Clean up "scripts" directory

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#7789]
This, me, week of 2017/01/17->?

- [ ] Make post modules out of any of the scripts that need to still be written as one
- [ ] Set expiration dates in all existing scripts
- [ ] Add powershell and python scripts directories

**Comment by egypt** [comment]
[ ] rm all the scripts that already have a post module counterpart

**Comment by void-in** [comment]
Following is the first go towards getting rid of the scripts directory.

Replacement of scripts inside the scripts/meterpreter directory:
```
arp_scanner.rb
<empty>

autoroute.rb
post/windows/manage/autoroute

checkvm.rb
post/windows/gather/checkvm

credcollect.rb
<empty>

domain_list_gen.rb
<empty>

dumplinks.rb
<empty>

duplicate.rb
post/windows/manage/payload_inject.rb
post/windows/manage/multi_meterpreter_inject.rb

enum_chrome.rb
post/windows/gather/enum_chrome.rb

enum_firefox.rb
post/windows/gather/enum_firefox.rb

enum_logged_on_users.rb
post/windows/gather/enum_logged_on_users.rb

enum_powershell_env.rb
post/windows/gather/enum_powershell_env.rb

enum_putty.rb
post/windows/gather/enum_putty_saved_sessions.rb

enum_shares
post/windows/gather/enum_shares.rb

enum_vmware.rb
<empty>

event_manager.rb
<empty>

file_collector.rb
post/windows/gather/enum_files.rb

get_application_list.rb
post/windows/gather/enum_applications.rb

getcountermeasures.rb
post/windows/manager/killav.rb

getenv.rb
<empty>

get_filezilla_creds.rb
post/windows/gather/credentials/filezilla_server.rb


get_pidgin_creds.rb
<empty>

getgui.rb
post/windows/manage/enable_rdp.rb

get_local_subnets.rb
post/windows/manage/autoroute.rb

get_pidgin_creds.rb
<empty>

gettelnet.rb
<empty>

get_valid_community.rb
post/windows/gather/enum_snmp.rb

getvncpw.rb
post/windows/gather/credentials/vnc.rb

hashdump.rb
post/windows/gather/smart_hashdump.rb

hostsedit.rb
post/windows/manage/inject_host.rb

keylogrecorder.rb
post/windows/capture/keylog_recorder.rb

killav.rb (duplicate of getcountermeasures - need to check)

metsvc.rb
post/windows/manage/persistence_exe.rb

migrate.rb
post/windows/manage/migrate.rb

multicommand.rb
<empty>

multi_console_command.rb
<empty>

multiscript.rb
<empty>

netenum.rb
<empty>

packetrecorder.rb
post/windows/manage/rpcapd_start.rb

panda_2007_pavsrv51.rb
<empty>

persistence.rb
post/window/manager/persistence_exe.rb

pml_driver_config.rb
<empty>

powerdump.rb
<empty>

prefetchtool.rb
post/windows/gather/enum_prefetch.rb

process_memdump.rb
post/windows/gather/memory_grep.rb

remotewinenum.rb
post/windows/gather/wmic_command.rb

scheduleme.rb
<empty>

schelevator.rb
exploits/windows/local/ms10_092_schelevator.rb

schtasksabuse.rb
<empty>

scraper.rb
post/windows/manage/autoroute
sysinfo command of meterpreter
post/windows/gather/tcpnetstat.rb
post/windows/gather/enum_shares.rb
post/windows/gather/enum_services.rb
post/windows/gather/smart_hashdump.rb

screenspy
post/windows/gather/screen_spy.rb

screen_unlock.rb
post/windows/escalate/screen_unlock.rb

search_dwld.rb
post/windows/gather/enum_files.rb

service_manager.rb
<empty>

service_permissions_escalate.rb
exploits/windows/local/service_permissions.rb

sound_recorder.rb
<empty>

srt_webdrive_priv.rb
<empty>

uploadexec.rb
post/windows/manage/download_exec.rb

virtualbox_sysenter_dos.rb
<empty>

virusscan_bypass.rb
<empty>

vnc.rb
<empty>

webcam.rb
post/windows/manage/webcam.rb

win32-sshclient.rb
<empty>

win32-sshserver.rb
<empty>

winbf.rb
<empty>

winenum.rb
post/windows/manage/autoroute
sysinfo command of meterpreter
post/windows/gather/tcpnetstat.rb
post/windows/gather/enum_shares.rb
post/windows/gather/enum_services.rb
post/windows/gather/smart_hashdump.rb

wmic.rb
post/windows/gather/wmic_command.rb
```
Would appreciate if a committer find a mistake in the above list or a module is available for a script where I have written ```<empty>``` to edit it inline so that we can have a single point to refer to. For non committers who don't have the edit options, just comment below and I will add it to the list.

**TODO**
Doing the same for ps, resource, and shell directories inside the scripts directory.

**Comment by bcoles** [comment]
`get_pidgin_creds.rb` appears in the list twice.

This script gets the creds, buddies and logs from Pidgin.

[post/multi/gather/pidgin_cred module](https://github.com/rapid7/metasploit-framework/tree/master/modules/post/multi/gather/pidgin_cred.rb) exists which gets the creds and buddies, but does not get the logs.

**Comment by bcoles** [comment]
[scripts/meterpreter/get_env.rb](https://github.com/rapid7/metasploit-framework/tree/master/scripts/meterpreter/get_env.rb) replaced by [modules/post/multi/gather/env.rb](https://github.com/rapid7/metasploit-framework/tree/master/modules/post/multi/gather/env.rb)

**Comment by fsacer** [comment]
Bug appeared in scripts/meterpreter/scheduleme.rb checking the prerequisites ` ==` vs `!=`.

**Comment by bcoles** [comment]
> 
> 
>     * [x]  rm all the scripts that already have a post module counterpart

I have a better idea: #11412

**Comment by bcoles** [comment]
The following scripts are yet to be deprecated:

```
arp_scanner
credcollect
domain_list_gen
dumplinks
enum_vmware
event_manager
get_pidgin_creds
gettelnet
multi_console_command
multi_meter_inject
multicommand
multiscript
netenum
panda_2007_pavsrv51
pml_driver_config
powerdump
process_memdump
scheduleme
schtasksabuse
scraper
service_manager
sound_recorder
srt_webdrive_priv
virtualbox_sysenter_dos
virusscan_bypass
vnc
winbf
winenum
```


```ruby
#!/usr/bin/env ruby
require 'json'

f = File.open('lib/msf/base/sessions/scriptable.rb', 'rb')
junk = f.read.scan(/^\s*def legacy_script_to_post_module\(script_name\)\s*\{(.*?)\}/m).flatten.first
f.close

scripts = []
junk.each_line do |line|
  next if line.strip.to_s == ''
  scripts << line.split('=>').first.strip.tr("'", '')
end
scripts.sort!

files = Dir.glob('./scripts/meterpreter/*.rb').select{ |e| File.file? e }.sort.each do |script|
  s = File.basename(script).strip.sub(/\.rb$/, '')
  puts s unless scripts.include? s
end
```
